nginx:
 dockerfile: ./Dockerfile # путь до докер файла указываем относительно директории в build
 build: ./containers/nginx
 ports:
  - 8000:80
 volumes:
  - ./logs:/etc/logs/nginx
 volumes_from:
  - fpm:rw
 environment:
  - NGINX_HOST=localhost
  - NGINX_PORT=80
 command: nginx -g "daemon off;" # Можно было указать в докер-фале, но можно и здесь)
 links:
  - fpm
fpm:
 dockerfile: ./Dockerfile
 build: ./containers/fpm
 volumes:
  - ./app:/var/www/app:rw
 links:
  - postgres
postgres:
 image: postgres:latest
 ports:
  - 5432:5432 # Проброс портов для внешнего доступа
 volumes:
  - ./database/postgres:/data/postgres
 environment:
  POSTGRES_PASSWORD: password
  POSTGRES_USER: postgres
  PGDATA : /data/postgres